CREATE DATABASE LOS

USE LOS


-- CHAMPSTATS 
CREATE TABLE CHAMPSTATS
(CHAMP_ID INT primary key,
HEALTH INT not null,
HEALTH_REGEN FLOAT not null,
AD INT not null,
RESSOURCE BIT not null,
ARMOR INT not null,
MR INT not null,
MVT_SPEED INT not null,
CAC BIT not null)

-- GAMEPLAYSTATS
CREATE TABLE GAMEPLAYSTATS
(HIGHEST_RANKED_PLAYER VARCHAR(15) primary key,
CHAMP_ID INT not null,
FOREIGN KEY(CHAMP_ID) REFERENCES CHAMPSTATS(CHAMP_ID),
META BIT not null,
RUNES VARCHAR(25) not null,
FIRST_SPELL_TAKEN CHAR not null,
FIRST_BLOOD FLOAT not null,
BEST_WIN_TIME VARCHAR(6) not null,
SUMMONER_SPELL VARCHAR(15) not null,
KDA FLOAT not null,
WIN_RATE FLOAT not null,
BAN_RATE FLOAT not null,
PICK_RATE FLOAT not null,
POST VARCHAR(8) not null)

-- METASTATS
CREATE TABLE METASTATS
(CHAMP_ID INT not null,
FOREIGN KEY(CHAMP_ID) REFERENCES CHAMPSTATS(CHAMP_ID),
HIGHEST_RANKED_PLAYER VARCHAR(15) not null,
FOREIGN KEY(HIGHEST_RANKED_PLAYER) REFERENCES GAMEPLAYSTATS(HIGHEST_RANKED_PLAYER),
RELEASE_DATE DATE not null,
CHAMP_TYPE VARCHAR(10) primary key,
DIFFICULTY INT not null,
EB_COST INT not null,
RP_COST INT not null,
NBR_SKIN INT not null,
PRO_PLAY INT null,
TOTAL_GAMES_PLAYED INT not null)

-- LORESTATS
CREATE TABLE LORESTATS
(CHAMP_ID INT not null,
FOREIGN KEY(CHAMP_ID) REFERENCES CHAMPSTATS(CHAMP_ID),
CHAMP_NAME VARCHAR(20) not null,
FULL_CHAMP_NAME VARCHAR(40) not null,
REGION VARCHAR(15) not null,
CHAMP_TYPE VARCHAR(10) not null,
FOREIGN KEY(CHAMP_TYPE) REFERENCES METASTATS(CHAMP_TYPE))

-- OBJECTIVES
CREATE TABLE OBJECTIVES
(DRAGONS_TAKEN INT null,
HEARLD_TAKEN INT null,
NASHOR_TAKEN INT null,
ELDER_DRAKE_TAKEN INT null,
RED_BUFF_TAKEN_FIRST BIT not null)

-- ITEMS
CREATE TABLE ITEMS
(CHAMP_ID INT not null,
FOREIGN KEY(CHAMP_ID) REFERENCES CHAMPSTATS(CHAMP_ID),
FIRST_ITEM_BUILT VARCHAR(40) not null,
FIRST_BOOTS_BUILT VARCHAR(40) null,
TOTAL_GP INT not null,
TOTAL_CS INT null) 

USE LOS

-- Alistar
INSERT CHAMPSTATS
VALUES(000, 600, 8.5, 62, 1, 44, 32, 330, 1)

-- Annie
INSERT CHAMPSTATS
VALUES(001, 524, 5.5, 50, 1, 19, 30, 335, 0)

-- Ashe
INSERT CHAMPSTATS
VALUES(002, 539, 3.5, 61, 1, 26, 30, 325, 0)

-- Fiddlesticks
INSERT CHAMPSTATS
VALUES(003, 580, 5.5, 55, 1, 34, 30, 335, 0)

-- Jax
INSERT CHAMPSTATS
VALUES(004, 592, 8.5, 68, 1, 36, 32, 350, 1)

-- Kayle
INSERT CHAMPSTATS
VALUES(005, 600, 5, 50, 1, 26, 34, 335, 1)

-- Maître Yi
INSERT CHAMPSTATS
VALUES(006, 598, 7.5, 66, 1, 33, 32, 355, 1)

-- Morgana
INSERT CHAMPSTATS
VALUES(007, 560, 5.5, 56, 1, 25, 30, 335, 0)

-- Nunu & Willump
INSERT CHAMPSTATS
VALUES(008, 570, 5, 61, 1, 32, 32, 345, 1)

-- Ryze
INSERT CHAMPSTATS
VALUES(009, 570, 8, 55, 1, 21, 34, 340, 0)

-- Sion
INSERT CHAMPSTATS
VALUES(010, 545, 7.5, 68, 1, 32, 32, 345, 1)

SELECT * FROM CHAMPSTATS

-- Alistar
INSERT GAMEPLAYSTATS
VALUES('Yokitch', 000, 1, 'Après-coup', 'Q', 0.15, 'Mid', 'Ignite', 6.16, 50.3, 0.5, 4.3, 'Support')

-- Annie
INSERT GAMEPLAYSTATS
VALUES('Meliodas Verde', 001, 0, 'Électrocution', 'Q', 0.30, 'Late', 'Ignite', 6.36, 52.0, 0.3, 1.8, 'Middle')

-- Ashe
INSERT GAMEPLAYSTATS
VALUES('Ganador', 002, 1, 'Tempo mortel', 'W', 0.40, 'Late', 'Heal', 6.43, 49.9, 0.5, 7.9, 'Bottom')

-- Fiddlesticks
INSERT GAMEPLAYSTATS
VALUES('Ferrari Fiddle', 003, 0, 'Prédateur', 'W', 0.56, 'Late', 'Smite', 6.63, 48.4, 23.5, 10.1, 'Jungle')

-- Jax
INSERT GAMEPLAYSTATS
VALUES('B1GBOPPA', 004, 1, 'Conquérant', 'E', 0.60, 'Mid', 'Teleport', 5.26, 48.8, 7.8, 10.5, 'Top')

-- Kayle
INSERT GAMEPLAYSTATS
VALUES('kayle 1v9', 005, 1, 'Jeu de jambes', 'E', 0.30, 'Mid', 'Teleport', 5.2, 49.8, 0.3, 2.9, 'Top')

-- Maître Yi
INSERT GAMEPLAYSTATS
VALUES('Zαpdo', 006, 1, 'Conquérant', 'Q', 0.35, 'Late', 'Smite', 6.2, 48.3, 25.2, 7.2, 'Jungle')

-- Morgana
INSERT GAMEPLAYSTATS
VALUES('Skylandz', 007, 1, 'Invocation d"Aery', 'W', 0.15, 'Mid', 'Ignite', 6.66, 51.0, 40.0, 10.5, 'Middle')

-- Nunu & Willump
INSERT GAMEPLAYSTATS
VALUES('Kesha', 008, 1, 'Prédateur', 'Q', 0.20, 'Early', 'Smite', 6.6, 50.8, 0.6, 3.3, 'Jungle')

-- Ryze
INSERT GAMEPLAYSTATS
VALUES('bruv machine', 009, 0, 'Rush phasique', 'W', 0.05, 'Late', 'Teleport', 5.33, 46.2, 0.9, 4.5, 'Middle')

-- Sion
INSERT GAMEPLAYSTATS
VALUES('Thebausffs', 010, 0, 'Poigne de l"immortel', 'Q', 0.30, 'Late', 'Teleport', 5.9, 50.4, 0.1, 2.7, 'Top')

SELECT * FROM GAMEPLAYSTATS